name: bookcatalog
description: Yet Another Books App

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_bloc: 7.3.3
  cached_network_image: ^3.2.2
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  collection: ^1.16.0


flutter:
  uses-material-design: true

  fonts:
    - family: BookifyIcons
      fonts:
        - asset: fonts/BookifyIcons.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
